name: values_object_and_failures_base
description: Utils to create  value objects and failures custom.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dartz: ^0.10.1
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  logger: ^1.1.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  build_runner: ^2.3.2
