name: pedido_listo_web
description: Client web Pedido Listo
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.2

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  values_object_and_failures_base:
    path: "./packages/values_object_and_failures_base"

  #=============================>
  # Core
  #=============================>
  freezed_annotation: ^2.1.0
  json_annotation: ^4.8.0
  logger: ^1.3.0
  go_router: ^7.0.1

  #=============================>
  # State
  #=============================>
  rxdart: ^0.27.7
  dartz: ^0.10.1
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  bloc_concurrency: ^0.2.1

  #=============================>
  # Firebase
  #=============================>

  cloud_firestore: ^4.7.0
  firebase_core: ^2.12.0

  #=============================>
  # Utils
  #=============================>
  google_fonts: ^4.0.3
  url_launcher: ^6.1.10
  path: ^1.8.2
  share_plus: ^7.0.2
  shared_preferences: ^2.1.1
  universal_html: ^2.2.2

  #=============================>
  # Widgets
  #=============================>
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.4.0
  shimmer: ^2.0.0
  built_collection: ^5.1.1
  flash: ^3.0.3+5
  flutter_blurhash: ^0.7.0
  flutter_native_splash: ^2.2.19

  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

dev_dependencies:
  build_runner: ^2.4.4
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

  freezed: ^2.2.0
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
