// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for fuchsia - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIcNyR5GQGf0Kd5iWiT8KacGzi4CsQQho',
    appId: '1:374233244738:web:810053a2dd8b47271439db',
    messagingSenderId: '374233244738',
    projectId: 'dev-pedidolisto',
    authDomain: 'dev-pedidolisto.firebaseapp.com',
    storageBucket: 'dev-pedidolisto.appspot.com',
    measurementId: 'G-MHVB2WW0WX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZp2mdUJRIGaxi_XfnbV6EPmly0Uxp1f4',
    appId: '1:374233244738:android:4d1f3d21dcd3d1b51439db',
    messagingSenderId: '374233244738',
    projectId: 'dev-pedidolisto',
    storageBucket: 'dev-pedidolisto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-cIMXU8FNYZVl0kbgA5ZHhBuVNtvx4sE',
    appId: '1:374233244738:ios:b6be83c64f895a251439db',
    messagingSenderId: '374233244738',
    projectId: 'dev-pedidolisto',
    storageBucket: 'dev-pedidolisto.appspot.com',
    androidClientId:
        '374233244738-oj8niseegc7f4ss3e7r8gp03mjbgake0.apps.googleusercontent.com',
    iosClientId:
        '374233244738-tqui45njg25kb9qliqfp3eg2p3nqf57h.apps.googleusercontent.com',
    iosBundleId: 'app.pedidolisto.pedido-listo-web',
  );
}
